data:
  query_data:
    beginTime: null
    duration: null
    num: '1'
    space_category[category_id]: '591'
    space_category[content_id]: '3'
plans: []
seat_list: []
session:
  headers:
    Accept: '*/*'
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-US,en;q=0.5
    Cache-Control: no-cache
    Connection: keep-alive
    Pragma: no-cache
    Referer: https://hdu.huitu.zhishulib.com/
    Sec-Fetch-Dest: empty
    Sec-Fetch-Mode: no-cors
    Sec-Fetch-Site: same-origin
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101
      Firefox/124.0
  params:
    LAB_JSON: '1'
  trust_env: false
  verify: false
settings:
  interval: 3
  max_try_times: 10
urls:
  book_seat: https://hdu.huitu.zhishulib.com/Seat/Index/bookSeats
  index: https://hdu.huitu.zhishulib.com/
  login: https://hdu.huitu.zhishulib.com/User/Index/login
  query_rooms: https://hdu.huitu.zhishulib.com/Space/Category/list
  query_seats: https://hdu.huitu.zhishulib.com/Seat/Index/searchSeats
user_info:
  login_name: '22010424'
  password: GXF22010424
